# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Hempnall
email: enq@hempnall.com
description: > # this means to ignore newlines until "baseurl:"
  Nothing terribly exciting... the odd technical blog post and news from Hempnall Information Systems
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.hempnall.com" # the base hostname & protocol for your site
twitter_username: hempnall
github_username:  hempnall

# Build settings
markdown: kramdown
